#!/usr/bin/env python3
"""MM P2 gen_m36 -- the DIMENSION-PARAMETERIZED trunk-family generator for
Qwen3.6-35B-A3B (hidden 2048; the dense-families retarget of MM_PLAN P2).

Emits the 2048-hidden dense families from dimension tables (the trunk tensors
are GGUF-native: Q8_0 projections / F32 router+norms / Q8_0 embed / Q6_K head):
  gv8k<NK>   Q8_0 GEMV, one warp per row, k = NK*32        (gv8k2048/4096/512)
  rmsz2048   RMSNormZeroCentered (1+w) variant, eps=fp32(1e-6)
  embg248    embed gather, vocab 248320 Q8_0 rows + clamp (image_token harmless)
  h8i2048    int8-g128 head-slice GEMV (scales fp32 [rows][16] + int8 rows)
Per-family build + cuobjdump audit (0 spill, REG report). The dense 27B
defaults are untouched -- this generator only emits MM_P2_* files.

Usage: ~/tg311/bin/python gen_m36.py [--build-only]
"""
import os, subprocess, sys

BASE = os.path.dirname(os.path.abspath(__file__))
BUILD = not ("--build-only" in sys.argv)  # always builds; flag kept for symmetry

# ---- dimension table: family -> (symbol, params, trunk tensors served) ----
GV8_TEMPLATE = r'''#include <cuda_fp16.h>
// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// gv8k{NK}: Q8_0 GEMV at k={KDIM} ({NK} x 34B blocks per row), one warp per row
// (32-row sweeps, 1024-thread CTAs). Per-lane elems {{b*32 + l}}, b asc running
// sums, xor-shfl tree; w = d*q dequant order; nvcc -fmad=false. y fp32.
// Serves: {SERVES}
extern "C" __global__ void __launch_bounds__(1024) {SYM}(
    const unsigned char* __restrict__ w,   // [rows][{NK}*34]
    const float* __restrict__ x,           // [{KDIM}]
    float* __restrict__ y,                 // [rows] fp32
    const int rows)
{{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int row = (blockIdx.x << 5) + warp;
  if (row < rows) {{
    const unsigned char* wr = w + (size_t)row*{ROWB};
    float a = 0.f;
    #pragma unroll {PRAG}
    for (int b = 0; b < {NK}; ++b) {{
      const float d = __half2float(*((const __half*)(wr + 34*b)));
      const signed char q = (const signed char)wr[34*b + 2 + lane];
      const float w_ = d * (float)q;
      a += w_ * x[(b << 5) + lane];
    }}
    #pragma unroll
    for (int o = 16; o > 0; o >>= 1) a += __shfl_xor_sync(0xffffffffu, a, o);
    if (lane == 0) y[row] = a;
  }}
}}
'''

RMSZ = r'''// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// rmsz2048: RMSNormZeroCentered variant (y = (x*rstd)*(1+w), rstd = 1/sqrtf(
// mean(x^2)+eps), eps = fp32(1e-6) from the GGUF kv). Per-thread strided
// partials {i + 256*t} t asc, warp xor trees, sequential sum of the 8 warp
// partials (warp asc); IEEE sqrtf + division (bit-exact vs the numpy port).
// The dense 27B norm default is UNCHANGED -- this is the manifest-selected
// (1+w) variant for qwen35moe.
extern "C" __global__ void __launch_bounds__(256) rmsz2048(
    const float* __restrict__ x,    // [P][2048]
    const float* __restrict__ w,    // [2048] F32
    float* __restrict__ y)          // [P][2048]
{
  const int p = blockIdx.x;
  const float* xr = x + (size_t)p*2048;
  const int th = threadIdx.x;
  __shared__ float wp[8];
  float s = 0.f;
  #pragma unroll
  for (int t = 0; t < 8; ++t) s += xr[th + (t << 8)] * xr[th + (t << 8)];
  #pragma unroll
  for (int o = 16; o > 0; o >>= 1) s += __shfl_xor_sync(0xffffffffu, s, o);
  if ((th & 31) == 0) wp[th >> 5] = s;
  __syncthreads();
  if (th == 0) {
    float a = wp[0];
    #pragma unroll
    for (int i = 1; i < 8; ++i) a += wp[i];
    const float ms = a * (1.0f/2048.0f);
    wp[0] = 1.0f / sqrtf(ms + 9.999999974752427e-07f);
  }
  __syncthreads();
  const float rstd = wp[0];
  #pragma unroll
  for (int t = 0; t < 8; ++t) {
    const int i = th + (t << 8);
    y[(size_t)p*2048 + i] = (xr[i] * rstd) * (1.0f + w[i]);
  }
}
'''

EMBG = r'''#include <cuda_fp16.h>
// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// embg248: embed gather, Q8_0 rows [248320][2176], y = d*q per elem (bit-exact
// the dq_q8_0 port). CLAMP: ids > 248319 -> 248319 (negative -> 0); the
// image_token id is harmless below vocab. One warp per token, 64 blocks.
extern "C" __global__ void __launch_bounds__(1024) embg248(
    const unsigned char* __restrict__ emb,  // [248320][2176]
    const int* __restrict__ ids,            // [P]
    float* __restrict__ y,                  // [P][2048]
    const int P)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int p = (blockIdx.x << 5) + warp;
  if (p < P) {
    int id = ids[p];
    if (id > 248319) id = 248319;
    if (id < 0) id = 0;
    const unsigned char* row = emb + (size_t)id*2176;
    float* yr = y + (size_t)p*2048;
    #pragma unroll 8
    for (int b = 0; b < 64; ++b) {
      const float d = __half2float(*((const __half*)(row + 34*b)));
      const signed char q = (const signed char)row[34*b + 2 + lane];
      yr[(b << 5) + lane] = d * (float)q;
    }
  }
}
'''

H8I = r'''// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// h8i2048: int8-g128 head-slice GEMV at hidden 2048 (16 groups x 128; scales
// fp32 [rows][16], int8 rows [rows][2048]; 4 consecutive int8 per lane per
// group as one 32-bit load). Running sums (g asc, j asc); -fmad=false.
// The SLICE SELECTION (which 40960 vocab rows) is P5 bring-up (tokenizer).
extern "C" __global__ void __launch_bounds__(1024) h8i2048(
    const signed char* __restrict__ wq,   // [rows][2048]
    const float* __restrict__ sc,         // [rows][16]
    const float* __restrict__ x,          // [2048]
    float* __restrict__ y,                // [rows]
    const int rows)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int row = (blockIdx.x << 5) + warp;
  if (row < rows) {
    const signed char* wr = wq + (size_t)row*2048;
    float a = 0.f;
    #pragma unroll
    for (int g = 0; g < 16; ++g) {
      const int q32 = *(const int*)(wr + (g << 7) + (lane << 2));
      const float s = sc[row*16 + g];
      #pragma unroll
      for (int j = 0; j < 4; ++j) {
        const signed char q = (signed char)((q32 >> (8*j)) & 0xFF);
        const float w_ = s * (float)q;
        a += w_ * x[(g << 7) + (lane << 2) + j];
      }
    }
    #pragma unroll
    for (int o = 16; o > 0; o >>= 1) a += __shfl_xor_sync(0xffffffffu, a, o);
    if (lane == 0) y[row] = a;
  }
}
'''

# family, symbol, NK, serves
GV8_FAMILIES = [
    ("gv8k2048", 64, "GDN in_proj_qkv [8192r x 2048k] (attn_qkv) + in_proj_z [4096r] (attn_gate); "
                 "attn q DOUBLED [8192r x 2048k] (rows 0..4095 Q | 4096..8191 gate -- consumer splits); "
                 "shared-expert gate/up [512r]; gv8k2048 also serves router F32 via rt8e256 (no gv8)..."
                 "+ embed rows (embg248 instead)" ),
    ("gv8k4096", 128, "GDN out_proj/ssm_out [2048r x 4096k]; attn k/v [512r x 2048k] use gv8k2048; "
                   "attn_output [2048r x 4096k] (post-attention out_proj)" ),
    ("gv8k512", 16, "shared-expert down [2048r x 512k] (the only k=512 GEMV)" ),
]

def emit(path, text):
    with open(path, "w") as f: f.write(text)
    print(f"[emit] {os.path.basename(path)}")

def build(src_stem):
    env = dict(os.environ, PATH=os.path.expanduser("~/.local/bin") + ":/opt/homebrew/bin:/usr/bin:/bin",
               DOCKER_HOST="unix://~/.colima/default/docker.sock")
    cu, cb = f"{BASE}/{src_stem}.cu", f"{BASE}/{src_stem}.cubin"
    r = subprocess.run(f"nvcc -arch=sm_86 -cubin -fmad=false --output-file={cb} {cu}",
                       shell=True, capture_output=True, text=True, env=env)
    if r.returncode: print(r.stderr[-1500:]); sys.exit(1)
    r = subprocess.run(["docker", "exec", "cuda-nvcc-persistent", "cuobjdump", "-res-usage", cb],
                       capture_output=True, text=True, env=env)
    line = ""
    for l in r.stdout.splitlines():
        if "Function" in l or "REG:" in l: line += l.strip() + " "
    ok = "SPILL-OK" if ("STACK:0" in line and "LOCAL:0" in line) else "SPILL!!"
    print(f"[build] {src_stem}: {ok} {line}"[:200])
    return 1 if ok == "SPILL-OK" else 0

def main():
    total_ok = 0
    for sym, nk, serves in GV8_FAMILIES:
        txt = GV8_TEMPLATE.format(SYM=sym, NK=nk, KDIM=nk*32, ROWB=nk*34, PRAG=8, SERVES=serves)
        emit(f"{BASE}/MM_P2_{sym}.cu", txt)
        total_ok += build(f"MM_P2_{sym}")
    emit(f"{BASE}/MM_P2_rmsz2048.cu", RMSZ);  total_ok += build("MM_P2_rmsz2048")
    emit(f"{BASE}/MM_P2_embg248.cu", EMBG);   total_ok += build("MM_P2_embg248")
    emit(f"{BASE}/MM_P2_h8i2048.cu", H8I);    total_ok += build("MM_P2_h8i2048")
    print(f"== gen_m36 done: {total_ok}/6 families SPILL-OK")

if __name__ == "__main__":
    main()
