// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// h8i2048: int8-g128 head-slice GEMV at hidden 2048 (16 groups x 128; scales
// fp32 [rows][16], int8 rows [rows][2048]; 4 consecutive int8 per lane per
// group as one 32-bit load). Running sums (g asc, j asc); -fmad=false.
// The SLICE SELECTION (which 40960 vocab rows) is P5 bring-up (tokenizer).
extern "C" __global__ void __launch_bounds__(1024) h8i2048(
    const signed char* __restrict__ wq,   // [rows][2048]
    const float* __restrict__ sc,         // [rows][16]
    const float* __restrict__ x,          // [2048]
    float* __restrict__ y,                // [rows]
    const int rows)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int row = (blockIdx.x << 5) + warp;
  if (row < rows) {
    const signed char* wr = wq + (size_t)row*2048;
    float a = 0.f;
    #pragma unroll
    for (int g = 0; g < 16; ++g) {
      const int q32 = *(const int*)(wr + (g << 7) + (lane << 2));
      const float s = sc[row*16 + g];
      #pragma unroll
      for (int j = 0; j < 4; ++j) {
        const signed char q = (signed char)((q32 >> (8*j)) & 0xFF);
        const float w_ = s * (float)q;
        a += w_ * x[(g << 7) + (lane << 2) + j];
      }
    }
    #pragma unroll
    for (int o = 16; o > 0; o >>= 1) a += __shfl_xor_sync(0xffffffffu, a, o);
    if (lane == 0) y[row] = a;
  }
}
