#include <cuda_fp16.h>
// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// embg248: embed gather, Q8_0 rows [248320][2176], y = d*q per elem (bit-exact
// the dq_q8_0 port). CLAMP: ids > 248319 -> 248319 (negative -> 0); the
// image_token id is harmless below vocab. One warp per token, 64 blocks.
extern "C" __global__ void __launch_bounds__(1024) embg248(
    const unsigned char* __restrict__ emb,  // [248320][2176]
    const int* __restrict__ ids,            // [P]
    float* __restrict__ y,                  // [P][2048]
    const int P)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int p = (blockIdx.x << 5) + warp;
  if (p < P) {
    int id = ids[p];
    if (id > 248319) id = 248319;
    if (id < 0) id = 0;
    const unsigned char* row = emb + (size_t)id*2176;
    float* yr = y + (size_t)p*2048;
    #pragma unroll 8
    for (int b = 0; b < 64; ++b) {
      const float d = __half2float(*((const __half*)(row + 34*b)));
      const signed char q = (const signed char)row[34*b + 2 + lane];
      yr[(b << 5) + lane] = d * (float)q;
    }
  }
}
