#include <cuda_fp16.h>
// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// gv8k64: Q8_0 GEMV at k=2048 (64 x 34B blocks per row), one warp per row
// (32-row sweeps, 1024-thread CTAs). Per-lane elems {b*32 + l}, b asc running
// sums, xor-shfl tree; w = d*q dequant order; nvcc -fmad=false. y fp32.
// Serves: GDN in_proj_qkv [8192r x 2048k] (attn_qkv) + in_proj_z [4096r] (attn_gate); attn q DOUBLED [8192r x 2048k] (rows 0..4095 Q | 4096..8191 gate -- consumer splits); shared-expert gate/up [512r]; gv8k2048 also serves router F32 via rt8e256 (no gv8)...+ embed rows (embg248 instead)
extern "C" __global__ void __launch_bounds__(1024) gv8k2048(
    const unsigned char* __restrict__ w,   // [rows][64*34]
    const float* __restrict__ x,           // [2048]
    float* __restrict__ y,                 // [rows] fp32
    const int rows)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int row = (blockIdx.x << 5) + warp;
  if (row < rows) {
    const unsigned char* wr = w + (size_t)row*2176;
    float a = 0.f;
    #pragma unroll 8
    for (int b = 0; b < 64; ++b) {
      const float d = __half2float(*((const __half*)(wr + 34*b)));
      const signed char q = (const signed char)wr[34*b + 2 + lane];
      const float w_ = d * (float)q;
      a += w_ * x[(b << 5) + lane];
    }
    #pragma unroll
    for (int o = 16; o > 0; o >>= 1) a += __shfl_xor_sync(0xffffffffu, a, o);
    if (lane == 0) y[row] = a;
  }
}
