#include <cuda_fp16.h>
// GENERATED by gen_m36.py -- DO NOT EDIT BY HAND.
// gv8k16: Q8_0 GEMV at k=512 (16 x 34B blocks per row), one warp per row
// (32-row sweeps, 1024-thread CTAs). Per-lane elems {b*32 + l}, b asc running
// sums, xor-shfl tree; w = d*q dequant order; nvcc -fmad=false. y fp32.
// Serves: shared-expert down [2048r x 512k]; attn k/v [512r x 512k] where k=512
extern "C" __global__ void __launch_bounds__(1024) gv8k512(
    const unsigned char* __restrict__ w,   // [rows][16*34]
    const float* __restrict__ x,           // [512]
    float* __restrict__ y,                 // [rows] fp32
    const int rows)
{
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  const int row = (blockIdx.x << 5) + warp;
  if (row < rows) {
    const unsigned char* wr = w + (size_t)row*544;
    float a = 0.f;
    #pragma unroll 8
    for (int b = 0; b < 16; ++b) {
      const float d = __half2float(*((const __half*)(wr + 34*b)));
      const signed char q = (const signed char)wr[34*b + 2 + lane];
      const float w_ = d * (float)q;
      a += w_ * x[(b << 5) + lane];
    }
    #pragma unroll
    for (int o = 16; o > 0; o >>= 1) a += __shfl_xor_sync(0xffffffffu, a, o);
    if (lane == 0) y[row] = a;
  }
}
